#!/usr/bin/env bash
# Post-process the buf-generated trees so they are consumable by their
# downstream build tools.
#
# - `proto/gen/go/`        : initialise a Go module so consumer modules
#                            can resolve it via a `replace` directive.
# - `proto/gen/python/`    : write a tiny pyproject.toml plus package
#                            __init__.py markers so uv can install the
#                            generated tree as an editable source.
#
# All artifacts produced here live under gitignored paths
# (see `.gitignore` and ADR-0007). The script is idempotent: re-running
# it produces byte-identical output.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
GEN_GO="${REPO_ROOT}/proto/gen/go"
GEN_PY="${REPO_ROOT}/proto/gen/python"

# ---------------------------------------------------------------------------
# Go: initialise the shared generated module (gitignored). Skipped on
# CI jobs that do not install Go (TypeScript, Python). The downstream
# Go consumers run their own bootstraps from CI jobs that do install
# Go, where this step is exercised.
# ---------------------------------------------------------------------------
if [ ! -d "${GEN_GO}" ]; then
  echo "post-generate: ${GEN_GO} not found; did 'buf generate' run?" >&2
  exit 1
fi

if command -v go >/dev/null 2>&1; then
  if [ ! -f "${GEN_GO}/go.mod" ]; then
    (cd "${GEN_GO}" && go mod init github.com/FabioCaffarello/spectre/proto/gen/go) >/dev/null
  fi
  # Pin the go directive to the project's minimum supported Go
  # version rather than the local toolchain's, so the consumer
  # modules — which also pin to the same minimum — can resolve the
  # replace target.
  (cd "${GEN_GO}" && go mod edit -go=1.24 && go mod tidy) >/dev/null
else
  echo "post-generate: 'go' not found on PATH; skipping Go module init in ${GEN_GO}." >&2
fi

# ---------------------------------------------------------------------------
# Python: stamp package init markers and write the editable-source
# pyproject.toml so the SeleniumBase adapter and the conformance suite
# can declare it as a uv source.
# ---------------------------------------------------------------------------
if [ ! -d "${GEN_PY}" ]; then
  echo "post-generate: ${GEN_PY} not found; did 'buf generate' run?" >&2
  exit 1
fi

mkdir -p "${GEN_PY}/spectre/driver/v1alpha1"
: >"${GEN_PY}/spectre/__init__.py"
: >"${GEN_PY}/spectre/driver/__init__.py"
: >"${GEN_PY}/spectre/driver/v1alpha1/__init__.py"

cat >"${GEN_PY}/pyproject.toml" <<'PYTOML'
# Generated by tools/codegen/post-generate.sh. Do not edit by hand.
# This file makes the buf-generated Python tree installable as an
# editable source so the SeleniumBase adapter and the conformance
# suite can import `spectre.driver.v1alpha1.*_pb2` modules.

[project]
name = "spectre-driver-protocol"
version = "0.0.0"
description = "Generated bindings for the Spectre Driver Protocol."
requires-python = ">=3.10"
dependencies = [
    "grpcio>=1.60",
    "protobuf>=4.25",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["spectre"]
PYTOML

